spring:
  # 配置redis服务器属性
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 15
    # 超时时间，单位毫秒
    timeout: 1000
    jedis:
      pool:
        # 最大连接数
        max-active: 10
        # 空闲连接数
        min-idle: 5
        max-idle: 10
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1